services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 181222
      POSTGRES_DB: task_nginx
    volumes:
      - db_data:/var/lib/postgresql/data
    # Map container 5432 to 5433 on the host to avoid conflicts with local Postgres
    ports:
      - '5433:5432'
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env
    depends_on:
      db:
        condition: service_healthy
    # Map to 3001 on the host to avoid conflicts with services already using 3000
    ports:
      - '3001:3000'
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - backend
    networks:
      - app-network

  nginx:
    image: nginx:stable
    ports:
      - '80:80'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge
